const SET_TOKEN = "SET_TOKEN"
const AUTH = "AUTH"
const FAIL_TO_AUTH = "FAIL_TO_AUTH"
const CASH_RESULTS = "CASH_RESULTS"
const UNSET_AUTH = "UNSET_AUTH"

export {
    SET_TOKEN,
    AUTH,
    FAIL_TO_AUTH,
    CASH_RESULTS,
    UNSET_AUTH
}